name: Generate and Update License Summary

on:
  push:
    branches:
      - main   # change to your branch if needed

jobs:
  license-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install license-checker globally
        run: npm install -g license-checker

      - name: Generate license JSON report
        run: license-checker --json > licenses.json

      - name: Generate LICENSES.md from JSON
        run: node generate-license-md.js

      - name: Commit LICENSES.md if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

          git add LICENSES.md

          echo "Git status:"
          git status

          echo "Git diff (staged):"
          git diff --cached || true

          if ! git diff --cached --exit-code; then
            git commit -m "Update LICENSES.md with latest license summary"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to LICENSES.md, skipping commit."
          fi
