# .github/workflows/license-report.yml
name: Generate NPM License Report

on:
  push:
    branches: [main]

jobs:
  license-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install license-checker
        run: npm install -g license-checker

      - name: Generate license report JSON
        run: license-checker --json > licenses.json

      - name: Generate HTML report
        run: |
          node generate-license-html.js

      - name: Upload license report
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: license-report.html
