# .github/workflows/npm-license-check.yml
name: NPM License Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-licenses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run license checker and generate report
        run: |
          npx license-checker --json > licenses.json
          cat licenses.json

      - name: Upload license report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: licenses.json
